[WIP ] Update project structure
iGene/openstack-exporter pull request #1
Opened 2018-06-08 14:21 UTC by kairen

2018-06-08 15:36 UTC, iGene commented on README.md
> +First clone the repo, and excute `Makefile` using make tool:
typo here, should be execute

2018-06-08 16:24 UTC, ching-kuo requested changes
RegionName should be pass to each collector to create its client, but this can be change later on.

There are other minor doc problems that should be addressed

2018-06-08 16:24 UTC, ching-kuo commented on README.md
> +First clone the repo, and excute `Makefile` using make tool:
Typo, should be execute

2018-06-08 16:24 UTC, ching-kuo commented on cmd/main.go
> +		os.Exit(1)
Could change to log.Fatalf for more consistency on logging.

2018-06-08 16:24 UTC, ching-kuo commented on README.md
>  - OpenStack Keystone Endpoint
Should change this part into 3 sections, each section describing how to configure it using the below methods.

1. Configuration file
2. Command line options
3. Environment variables

Also there's a typo (configraion -> configration)

2018-06-10 14:13 UTC, ching-kuo requested changes
Besides some minor problems, coding part LGTM

2018-06-10 14:13 UTC, iGene commented on README.md
> +First clone the repo, and should be execute `Makefile` using make tool:
should be execute -> execute

2018-06-10 14:13 UTC, iGene commented on cmd/main.go
>  	pflag.StringVar(&region, "region-name", os.Getenv("OS_REGION_NAME"), "Region Name for the OpenStack Keystone.")
for the OpenStack Keystone -> for OpenStack Keystone

2018-06-10 14:13 UTC, iGene commented on README.md
> +Should change this part into 3 sections to selecting each section describing how to configure it using the below methods.
Change it to
"Configuring OpenStack exporter can be done in 3 ways, choose the one that is suitable for your environment."

2018-06-10 14:22 UTC, ching-kuo approved these changes

2018-06-10 14:22 UTC, ching-kuo commented
LGTM

2018-06-10 14:22 UTC, merged